# basic info
title: Jeffrey's Portfolio
description: My data science portfolio

# contacts
email: curious.cruncher@gmail.com
github: curious-jeff

url: https://curious-jeff.github.io
theme: jekyll-theme-tactile

